---
- name: Execute Dev-Ops script
  hosts: ubuntu-002
  become: yes

  tasks:

    - template: src=~/git/ansible/hh-personal-try/templates/apt.conf dest=/etc/apt/apt.conf

    - name: Show Version
      command: lsb_release -a
      register: os_version

    - name: Print OS Version
      debug: var=os_version.stdout_lines
    
    - name: Get Update
      apt: update_cache=yes

    - name: Get Dist Upgrade
      apt: upgrade=dist  
   
    - name: Execute Reboot
      command: shutdown -r

    - name: Wait for Machine to come back up
      become: false
      local_action:
        module: wait_for
          host={{ ansible_ssh_host }}
          port={{ ansible_ssh_port | default(22) }}
          delay=10

    - name: Show Version
      command: lsb_release -a
      register: os_version

    - name: Print Version
      debug: var=os_version.stdout_lines

    - name: Get Uptime
      shell: uptime
      register: result

    - name: Print Uptime
      debug: var=result.stdout_lines
